# Generated by Django 4.2.1 on 2024-06-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_apellido_usuario_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieza',
            name='imagen_pieza',
            field=models.ImageField(blank=True, null=True, upload_to='pieza_fotos/'),
        ),
    ]
