# Generated by Django 4.2.1 on 2024-06-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='Sin Apellido', max_length=255),
        ),
    ]
